// Mocks generated by Mockito 5.4.4 from annotations
// in project1/test/products_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project1/core/network/api/products_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductDTO_0 extends _i1.SmartFake implements _i2.ProductDTO {
  _FakeProductDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsApi extends _i1.Mock implements _i2.ProductsApi {
  MockProductsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.ProductDTO>> getProducts(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [
            page,
            limit,
          ],
        ),
        returnValue: _i3.Future<List<_i2.ProductDTO>>.value(<_i2.ProductDTO>[]),
      ) as _i3.Future<List<_i2.ProductDTO>>);

  @override
  _i3.Future<_i2.ProductDTO> getProductById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i3.Future<_i2.ProductDTO>.value(_FakeProductDTO_0(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i3.Future<_i2.ProductDTO>);

  @override
  _i3.Future<_i2.ProductDTO> createProduct(_i2.CreateProductRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [request],
        ),
        returnValue: _i3.Future<_i2.ProductDTO>.value(_FakeProductDTO_0(
          this,
          Invocation.method(
            #createProduct,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.ProductDTO>);

  @override
  _i3.Future<_i2.ProductDTO> updateProduct(
    String? id,
    _i2.UpdateProductRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            id,
            request,
          ],
        ),
        returnValue: _i3.Future<_i2.ProductDTO>.value(_FakeProductDTO_0(
          this,
          Invocation.method(
            #updateProduct,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i3.Future<_i2.ProductDTO>);

  @override
  _i3.Future<void> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.ProductDTO>> searchProducts(
    String? query,
    String? category,
    Map<String, dynamic>? filters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [
            query,
            category,
            filters,
          ],
        ),
        returnValue: _i3.Future<List<_i2.ProductDTO>>.value(<_i2.ProductDTO>[]),
      ) as _i3.Future<List<_i2.ProductDTO>>);
}
